[package]
name = "sync-rs"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dialoguer = { version = "0.11", features = ["fuzzy-select"] }
dirs = "5"
indicatif = "0.17"
